### ISSUE TITLE
Check `bpy` save and load to handle `.blender` file

### ISSUE THREAD

**Issue by skim0119** [GazzolaLab/Blender-Soft-Rod#4]
## Tasks

- [x] install bpy and setup python environment
- [x] Check if saving and loading `.blender` file is possible with `bpy` package
- [x] Write unit-test using `pytest`
  - [x] Create `tests` directory
  - [x] Create test files for file handling `test_file_handling.py`

## For later

- Decide API

## Reference

- Read `pytest`
- Read `Test Driven Development` or `Behavior Driven Development` concept
- https://docs.blender.org/api/current/info_advanced_blender_as_bpy.html#limitations
